[package]
name = "tokio-stream"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { workspace = true }
common = { path = "../common" }
futures = { workspace = true }
log = { workspace = true }
rand = "0.8.5"
rdkafka = { workspace = true }
tokio = { workspace = true }
