[package]
name = "zeou"
version = "0.1.0"
edition.workspace = true

[dependencies]
lib = { path = "../lib" }
log = { workspace = true }
rdkafka = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
