[package]
name = "tokio-consumer"
version = "0.1.0"
edition.workspace = true

[dependencies]
clap = { workspace = true }
lib = { path = "../lib" }
futures = { workspace = true }
log = { workspace = true }
rdkafka = { workspace = true }
tokio = { workspace = true }
